import type { Metadata } from 'next'
import { Geist, Geist_Mono, Bitter } from 'next/font/google'
import '@/app/globals.css'
import Navbar from '@/components/navbar/Navbar'
import Web3Provider from '@/components/Web3Provider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

const bitter = Bitter({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-bitter',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} ${bitter.variable} antialiased`}
      >
        <Web3Provider>
          <Navbar />
          {children}
        </Web3Provider>
      </body>
    </html>
  )
}
